# Autogenerated wrapper script for web3go_jll for i686-w64-mingw32
export web3

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("web3go")
JLLWrappers.@declare_executable_product(web3)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_executable_product(
        web3,
        "bin\\web3.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
